[package]
name = "popcorn"
version = "0.1.0"
edition = "2021"
authors = ["The Popcorn Team"]
license = "GNU General Public License"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"
bootloader = "0.9.7"
x86_64 = "0.14.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]



[package.metadata.bootimage]
build-command = ["build"]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}"]
