name: Delete Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Branch
        run: |
          git branch -d ${{ github.event.pull_request.head.ref }}

