name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: Check
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly
    steps:
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Install bootimage
        run: cargo install bootimage --debug
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Rustup Components
        run: rustup component add rust-src llvm-tools-preview

      # install QEMU
      - name: Install QEMU (Linux)
        run: sudo apt update && sudo apt install qemu-system-x86
        if: runner.os == 'Linux'
      - name: Install QEMU (macOS)
        run: brew install qemu
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Install QEMU (Windows)
        run: |
          choco install qemu --version 2021.5.5
          echo "$Env:Programfiles\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: runner.os == 'Windows'
        shell: pwsh
      - name: "Print QEMU Version"
        run: qemu-system-x86_64 --version

      - name: Run `cargo test`
        run: cargo test --verbose

  clippy:
    runs-on: ${{ matrix.os }}
    name: Clippy
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Clippy
      run: cargo clippy --verbose --all