name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  rust_linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy --verbose
    - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
