name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  check:
    runs-on: ${{ matrix.os }}
    name: Check
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            rust: nightly
    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  format:
    runs-on: ${{ matrix.os }}
    name: Format
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Format
      run: cargo fmt --verbose --all -- --check

  clippy:
    runs-on: ${{ matrix.os }}
    name: Clippy
    strategy:
      matrix:
        include:
          # Ubuntu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rust: nightly

    steps:
    - uses: actions/checkout@v2
    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
    - name: Add nightly-x86_64
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - name: Clippy
      run: cargo clippy --verbose --all -- --deny warnings